#pragma once

#define OVERPLUS_VER_MAJOR 2
#define OVERPLUS_VER_MINOR 0
#define OVERPLUS_VER_PATCH 1

#define OVERPLUS_VERSION (OVERPLUS_VER_MAJOR * 10000 + OVERPLUS_VER_MINOR * 100 + OVERPLUS_VER_PATCH)
inline const char* OVERPLUS_VERSION_STR = "v2.0.1";

