#pragma once

#define OVERPLUS_VER_MAJOR 1
#define OVERPLUS_VER_MINOR 1
#define OVERPLUS_VER_PATCH 0

#define OVERPLUS_VERSION (OVERPLUS_VER_MAJOR * 10000 + OVERPLUS_VER_MINOR * 100 + OVERPLUS_VER_PATCH)
const char* OVERPLUS_VERSION_STR ="v1.1.0";

